/**
 * System + per-pass prompts for the ZK circuit auditor.
 *
 * The prompts encode the auditor's identity and the multi-pass
 * pipeline (recon/intent -> constraint extraction -> soundness check
 * -> scoring) and force JSON output where structured data is required.
 */

const SYSTEM_PROMPT = [
  "You are a senior zero-knowledge circuit auditor.",
  "You audit Circom, Noir, and Halo2 circuits for soundness, with a",
  "primary focus on UNDER-CONSTRAINED SIGNALS — the #1 ZK bug class",
  "where a circuit accepts invalid witnesses because a constraint is",
  "missing, even though it 'works' on valid inputs. Compilers and tests",
  "do not catch this; semantic reasoning does.",
  "",
  "Your job is INFER THE CIRCUIT'S INTENT, then check whether the",
  "constraint system actually enforces it. The gap between intent and",
  "constraints is the bug.",
  "",
  "Always respond with strict JSON matching the requested schema. No",
  "prose, no markdown, no code fences. The caller parses the response",
  "as JSON.",
  "",
  "For each finding, include:",
  "  - severity: 'critical' | 'high' | 'medium' | 'low' | 'info'",
  "  - category: short slug (e.g. 'under-constrained', 'missing-range-check')",
  "  - title: one-line human title",
  "  - signal: optional name of the offending signal/identifier",
  "  - line: optional 1-based line number",
  "  - description: 1-3 sentences explaining the weakness and how a",
  "    malicious prover could exploit it",
  "  - fix: concrete suggested fix (text or short code)",
  "  - weaknessId: one of the ZK Weakness Classification ids:",
  "    ZKWC-001 .. ZKWC-015",
  "",
  "Be specific. Cite signal names and line numbers. Do not invent",
  "signals that do not exist. If the circuit looks sound, say so and",
  "return an empty findings array — do not pad.",
].join(" ");

const LANG_HINTS = {
  circom: [
    "Language: Circom 2.x.",
    "  - <-- is witness assignment only (no constraint).",
    "  - <== / === are constraints.",
    "  - signal input/output/intermediate visibility matters.",
    "  - Pay attention to templates, component instantiation, and",
    "    any signal declared `output` that is not pinned by a",
    "    matching constraint.",
  ].join("\n"),
  noir: [
    "Language: Noir (Aztec).",
    "  - Constraints are auto-generated from regular Rust-like code.",
    "  - Look for unconstrained functions, unconstrained assertions,",
    "    public outputs that are not tied to private witnesses,",
    "    missing `let` rebinds, and loops with unknown bounds.",
    "  - `assert(...)` only adds a constraint; a missing assert is a",
    "    missing constraint.",
  ].join("\n"),
  halo2: [
    "Language: Halo2 (Rust DSL).",
    "  - Custom gates, lookup arguments, and permutation arguments.",
    "  - Look for regions/cells that are assigned (`assign_region`) but",
    "    not gated, copy-constraints missing between cells, lookups",
    "    that don't enforce table inclusion, and equality constraints",
    "    that allow aliasing.",
  ].join("\n"),
};

function reconUserPrompt(source, lang) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK 1: RECON & INTENT",
    "",
    "Read the circuit. In one short paragraph, summarize:",
    "  1. what the circuit claims to prove,",
    "  2. its public inputs/outputs and private inputs,",
    "  3. the prover's intended behavior.",
    "",
    "Then return strict JSON:",
    "{",
    '  "intent": string,',
    '  "publicSignals": [string],',
    '  "privateSignals": [string],',
    '  "summary": string',
    "}",
    "",
    hint,
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

function constraintExtractionUserPrompt(source, lang, recon) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK 2: CONSTRAINT EXTRACTION",
    "",
    "Walk the circuit and extract a structured map:",
    "  - For every signal, list the constraints that pin its value.",
    "  - Note visibility (public / private / intermediate / output).",
    "  - Note any signals that are assigned but have NO constraint.",
    "  - Note any <-- in Circom that lacks a matching === (ZKWC-008).",
    "",
    "Return strict JSON:",
    "{",
    '  "signals": [',
    "    {",
    '      "name": string,',
    '      "visibility": "public"|"private"|"intermediate"|"output",',
    '      "constraints": [string],',
    '      "unconstrained": boolean,',
    '      "notes": string',
    "    }",
    "  ],",
    '  "danglingSignals": [string]',
    "}",
    "",
    hint,
    "",
    "## RECON (FROM TASK 1)",
    JSON.stringify(recon, null, 2),
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

function soundnessUserPrompt(source, lang, recon, constraints) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK 3: SOUNDNESS CHECK (INTENT vs CONSTRAINTS)",
    "",
    "Compare the circuit's intent (from Task 1) with the constraint",
    "map (from Task 2). Find the GAP. Specifically check for:",
    "",
    "  - Under-constrained output signals (ZKWC-001).",
    "  - Unconstrained signals (ZKWC-002).",
    "  - Missing range checks (ZKWC-003).",
    "  - Missing boolean / bit constraints (ZKWC-004).",
    "  - Nondeterminism / aliasing (ZKWC-005).",
    "  - Unsafe component reuse (ZKWC-006).",
    "  - Dangling / dead signals (ZKWC-007).",
    "  - <-- without matching === (ZKWC-008).",
    "  - Public input not bound to private witness (ZKWC-009).",
    "  - Incomplete conditional / if-then-else soundness (ZKWC-010).",
    "  - Lookup / permutation misuse (ZKWC-011).",
    "  - Division-by-zero / inverse risk (ZKWC-012).",
    "  - Cross-language translation issue (ZKWC-013) where applicable.",
    "  - Weak hash / Pedersen / MiMC params (ZKWC-014).",
    "  - Trusted setup / toxic waste risk (ZKWC-015).",
    "",
    "For EACH finding, return an object with:",
    "  severity, category, title, signal?, line?, description, fix,",
    "  weaknessId (one of ZKWC-001 .. ZKWC-015).",
    "If there are no findings, return an empty array — do not pad.",
    "",
    "Return strict JSON:",
    "{",
    '  "findings": [ ... ]',
    "}",
    "",
    hint,
    "",
    "## RECON",
    JSON.stringify(recon, null, 2),
    "",
    "## CONSTRAINT MAP",
    JSON.stringify(constraints, null, 2),
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

function scoringUserPrompt(findings) {
  return [
    "## TASK 4: SOUNDNESS SCORE",
    "",
    "Given the findings from Task 3, compute an overall soundness",
    "score from 0 to 100 where 100 means the circuit is fully sound",
    "(no findings, every signal is fully constrained, intent matches",
    "constraints exactly).",
    "",
    "Use this rubric:",
    "  - Start at 100.",
    "  - critical finding: -25 each (min 0).",
    "  - high finding:     -10 each (min 0).",
    "  - medium finding:   -4 each  (min 0).",
    "  - low finding:      -1 each  (min 0).",
    "  - info: no deduction.",
    "  - Clamp to [0, 100].",
    "",
    "Return strict JSON:",
    "{",
    '  "soundnessScore": number,',
    '  "summary": string',
    "}",
    "",
    "## FINDINGS",
    JSON.stringify(findings, null, 2),
  ].join("\n");
}

function explainUserPrompt(source, lang) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK: EXPLAIN THIS CIRCUIT",
    "",
    "Produce a plain-English explanation of the circuit for a smart",
    "developer who has never read it. Include:",
    "  1. What the circuit proves (one short paragraph).",
    "  2. Its public signals and their meaning.",
    "  3. Its private signals (witness) and their meaning.",
    "  4. A signal -> constraint map (which signals are pinned and how).",
    "  5. Anything subtle a reviewer should look at first.",
    "",
    "Return strict JSON:",
    "{",
    '  "summary": string,',
    '  "publicSignals": [{ "name": string, "meaning": string }],',
    '  "privateSignals": [{ "name": string, "meaning": string }],',
    '  "signalToConstraintMap": [{ "signal": string, "constrainedBy": string }],',
    '  "reviewerNotes": [string]',
    "}",
    "",
    hint,
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

function targetedCheckUserPrompt(source, lang, concern) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK: TARGETED CONCERN CHECK",
    "",
    "The reviewer is specifically asking:",
    `  > ${concern}`,
    "",
    "Audit the circuit with that specific question in mind. Focus on",
    "the smallest possible change to make the circuit enforce the",
    "reviewer's intent. If the circuit already enforces it, say so.",
    "",
    "Return strict JSON:",
    "{",
    '  "concern": string,',
    '  "verdict": "sound" | "unsound" | "inconclusive",',
    '  "explanation": string,',
    '  "findings": [',
    "    {",
    '      "severity": "critical"|"high"|"medium"|"low"|"info",',
    '      "category": string,',
    '      "title": string,',
    '      "signal": string,',
    '      "line": number,',
    '      "description": string,',
    '      "fix": string,',
    '      "weaknessId": "ZKWC-001".."ZKWC-015"',
    "    }",
    "  ]",
    "}",
    "",
    hint,
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

function suggestConstraintsUserPrompt(source, lang, recon) {
  const hint = LANG_HINTS[lang] || LANG_HINTS.circom;
  return [
    "## TASK: SUGGEST MISSING CONSTRAINTS",
    "",
    "Look at the circuit and propose the MINIMAL set of additional",
    "constraints (or, in Noir/Halo2, code-level additions) that would",
    "make the circuit sound. Prefer the smallest fix that closes the",
    "intent-vs-constraint gap.",
    "",
    "For each suggestion return:",
    "  - weaknessId (ZKWC-001 .. ZKWC-015)",
    "  - title",
    "  - rationale (1-2 sentences)",
    "  - codeSnippet (the exact code to add / change, in the same",
    "    language as the source). For Circom, include the matching",
    "    === for any <-- where possible.",
    "  - location: where to place it (signal name, line, or 'after X')",
    "",
    "Return strict JSON:",
    "{",
    '  "suggestions": [',
    "    {",
    '      "weaknessId": string,',
    '      "title": string,',
    '      "rationale": string,',
    '      "codeSnippet": string,',
    '      "location": string',
    "    }",
    "  ]",
    "}",
    "",
    hint,
    "",
    "## RECON (IF AVAILABLE)",
    JSON.stringify(recon || {}, null, 2),
    "",
    "## CIRCUIT SOURCE",
    "```",
    source,
    "```",
  ].join("\n");
}

module.exports = {
  SYSTEM_PROMPT,
  LANG_HINTS,
  reconUserPrompt,
  constraintExtractionUserPrompt,
  soundnessUserPrompt,
  scoringUserPrompt,
  explainUserPrompt,
  targetedCheckUserPrompt,
  suggestConstraintsUserPrompt,
};
